services:
  mongodb:
    image: mongo:latest
    container_name: karateflow-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: karateflow_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    image: maven:3-eclipse-temurin-25
    container_name: karateflow-api
    working_dir: /app
    volumes:
      # Monta il codice locale per poter eseguire mvn spring-boot:run
      - .:/app
      # Usa un volume per scaricare le dipendenze Maven una sola volta
      - maven_repo:/root/.m2
    ports:
      - "8080:8080"
      - "5005:5005" # Porta per collegare il debugger del tuo IDE
    environment:
      # Sovrascrive localhost con il nome del container database
      SPRING_DATA_MONGODB_HOST: mongodb
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  maven_repo:
