spring.application.name=backend

# Configurazione esplicita per MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=karateflow_db
spring.data.mongodb.username=admin
spring.data.mongodb.password=password
spring.data.mongodb.authentication-database=admin

# Test e Log
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
logging.level.org.mongodb.driver=DEBUG
test.messaggio=STO_LEGGENDO_LE_PROPERTIES