spring.application.name=backend

# Configurazione esplicita per MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:}
spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:localhost}
spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT:27017}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:karateflow_db}
spring.data.mongodb.username=${SPRING_DATA_MONGODB_USERNAME:admin}
spring.data.mongodb.password=${SPRING_DATA_MONGODB_PASSWORD:password}
spring.data.mongodb.authentication-database=${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}

# Test e Log
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
logging.level.org.mongodb.driver=DEBUG
test.messaggio=STO_LEGGENDO_LE_PROPERTIES

# CORS Configuration
app.cors.allowed-origins=http://localhost:4200